Get Terraform out of the CI/CD business (#406)
* Build containers separately

* Fail on errors requesting the secret

* Do not manage the lifecycle of Cloud Run services

* Remove unused secrets, more POLP

* Remove triggers

* Add ability to deploy single service

* Add ability to promote a single service

* Update docs + remote state

* Remove state.tf

* Fix GCR link

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -17,12 +17,35 @@
 set -eEuo pipefail
 
 ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"
+ALL_SERVICES="cleanup-export,cleanup-exposure,export,exposure,federationin,federationout"
 
 if [ -z "${PROJECT_ID:-}" ]; then
   echo "✋ Missing PROJECT_ID!" >&2
   exit 1
 fi
 
-gcloud builds submit "${ROOT}" \
-  --config "${ROOT}/builders/build.yaml" \
-  --project "${PROJECT_ID}"
+if [ -z "${SERVICES:-}" ]; then
+  echo "✋ Missing SERVICES!" >&2
+  exit 1
+fi
+
+if [ "${SERVICES}" == "all" ]; then
+  SERVICES=${ALL_SERVICES}
+  echo "🚧 Building all services! (${SERVICES})" >&2
+fi
+
+if [ -z "${TAG:-}" ]; then
+  TAG="$(date '+%Y%m%d%H%M%S')"
+  echo "🚧 Using generated tag! (${TAG})" >&2
+fi
+
+IFS=',' read -ra SERVICES_ARR <<< "${SERVICES}"
+for SERVICE in "${SERVICES_ARR[@]}"; do
+  gcloud builds submit "${ROOT}" \
+    --project "${PROJECT_ID}" \
+    --config "${ROOT}/builders/build.yaml" \
+    --substitutions "_SERVICE=${SERVICE},_TAG=${TAG}" \
+    &
+done
+
+wait
diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -17,6 +17,7 @@
 set -eEuo pipefail
 
 ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"
+ALL_SERVICES="cleanup-export,cleanup-exposure,export,exposure,federationin,federationout"
 
 if [ -z "${PROJECT_ID:-}" ]; then
   echo "✋ Missing PROJECT_ID!" >&2
@@ -28,7 +29,28 @@ if [ -z "${REGION:-}" ]; then
   exit 1
 fi
 
-gcloud builds submit "${ROOT}" \
-  --config "${ROOT}/builders/deploy.yaml" \
-  --substitutions "_REGION=${REGION}" \
-  --project "${PROJECT_ID}"
+if [ -z "${SERVICES:-}" ]; then
+  echo "✋ Missing SERVICES!" >&2
+  exit 1
+fi
+
+if [ "${SERVICES}" == "all" ]; then
+  SERVICES="${ALL_SERVICES}"
+  echo "🚧 Building all services! (${SERVICES})" >&2
+fi
+
+if [ -z "${TAG:-}" ]; then
+  TAG="$(date '+%Y%m%d%H%M%S')"
+  echo "🚧 Using generated tag! (${TAG})" >&2
+fi
+
+IFS=',' read -ra SERVICES_ARR <<< "${SERVICES}"
+for SERVICE in "${SERVICES_ARR[@]}"; do
+  gcloud builds submit --no-source \
+    --project "${PROJECT_ID}" \
+    --config "${ROOT}/builders/deploy.yaml" \
+    --substitutions "_REGION=${REGION},_SERVICE=${SERVICE},_TAG=${TAG}" \
+    &
+done
+
+wait
